Running on host gpu32.bc4.acrc.priv
Slurm job ID is 3602022
This job runs on the following machines:
gpu32
Obtaining file:///mnt/storage/home/mk17486/neural-networks/pytorch-subLSTM
Requirement already satisfied: numpy in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages (from torch-sublstm==0.1.0) (1.18.1)
Requirement already satisfied: torch in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages (from torch-sublstm==0.1.0) (1.4.0)
Installing collected packages: torch-sublstm
  Found existing installation: torch-sublstm 0.1.0
    Uninstalling torch-sublstm-0.1.0:
      Successfully uninstalled torch-sublstm-0.1.0
  Running setup.py develop for torch-sublstm
Successfully installed torch-sublstm
subLSTMCuda
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    model = model.RNNModel(args.model, ntokens, args.emsize, args.nhid, args.nlayers, args.dropout, args.tied, args.batch_size)
  File "/mnt/storage/home/mk17486/neural-networks/pytorch-subLSTM/tasks/word_language_model/model.py", line 37, in __init__
    batch_size=batch_size)
  File "../../src/subLSTM/basic/nn.py", line 222, in __init__
    traced_layer = torch.jit.trace(layer, (INPUT,STATE))
  File "/mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/jit/__init__.py", line 1034, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "../../src/subLSTM/basic/nn.py", line 95, in forward
    new_h, new_cell = torch.ops.sublstm.apply(input, self.weights, self.bias, *state)
RuntimeError: Found an unsupported argument type c10::List<at::Tensor> in the JIT tracer. File a bug report. (addOutput at /pytorch/torch/csrc/jit/tracer.h:319)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x2b326e0a0193 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x40eb05d (0x2b32ae85f05d in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x40e9150 (0x2b32ae85d150 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6df26f (0x2b32a9df026f in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6aa484 (0x2b32a9dbb484 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x295a74 (0x2b32a99a6a74 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: <unknown function> + 0x75ce03 (0x2b32a9e6de03 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #23: torch::jit::tracer::trace(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::function<std::vector<c10::IValue, std::allocator<c10::IValue> > (std::vector<c10::IValue, std::allocator<c10::IValue> >)> const&, std::function<std::string (at::Tensor const&)>, bool, torch::jit::script::Module*) + 0x4e6 (0x2b32aea8b9e6 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #24: <unknown function> + 0x759091 (0x2b32a9e6a091 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #25: <unknown function> + 0x7728e2 (0x2b32a9e838e2 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #26: <unknown function> + 0x295a74 (0x2b32a99a6a74 in /mnt/storage/home/mk17486/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #56: __libc_start_main + 0xf5 (0x2b326895bb35 in /usr/lib64/libc.so.6)

